from __future__ import annotations

from fastapi import APIRouter
from sqlalchemy import or_

from app.database import SessionLocal
from app.models import Alert, AuditLog, Incident, Resource
from app.schemas import DemoScenarioRequest
router = APIRouter(prefix="/demo", tags=["demo"])


@router.get("/scenarios")
def list_scenarios():
    return {
        "scenarios": [
            {"id": "rainfall-rise", "label": "Heavy rainfall and rising river levels", "simulated": True},
            {"id": "multiple-reports", "label": "Multiple emergency reports in a vulnerable area", "simulated": True},
            {"id": "limited-resources", "label": "Limited rescue resources across multiple incidents", "simulated": True},
        ]
    }


@router.post("/replay")
def replay_scenario(payload: DemoScenarioRequest | None = None):
    scenario = payload.scenario if payload else "rainfall-rise"
    db = SessionLocal()
    try:
        incidents = [
            Incident(name="River watch: Godavari", location="Rajahmundry", latitude=16.9891, longitude=81.7842, severity="critical", status="open", priority_score=0.91, notes="Synthetic demo record", source="demo"),
            Incident(name="Urban drainage watch", location="Mumbai", latitude=19.0760, longitude=72.8777, severity="high", status="monitoring", priority_score=0.74, notes="Synthetic demo record", source="demo"),
            Incident(name="Low-lying road report", location="Hyderabad", latitude=17.3850, longitude=78.4867, severity="medium", status="open", priority_score=0.56, notes="Synthetic demo record", source="demo"),
            Incident(name="Coastal shelter readiness", location="Chennai", latitude=13.0827, longitude=80.2707, severity="low", status="monitoring", priority_score=0.28, notes="Synthetic demo record", source="demo"),
        ]
        resources = [
            Resource(name="NDRF response unit", resource_type="Rescue team", quantity=3, capacity=4, availability=3, location="Hyderabad", status="available"),
            Resource(name="Inflatable rescue boats", resource_type="Water rescue", quantity=8, capacity=8, availability=6, location="Rajahmundry", status="available"),
            Resource(name="Medical support kits", resource_type="Medical", quantity=24, capacity=30, availability=18, location="Mumbai", status="available"),
        ]
        alerts = [
            Alert(title="River level threshold watch", severity="critical", affected_locations="Rajahmundry", message="Synthetic alert for tabletop exercise. Validate against official sources before action.", language="en", simulated=True, status="draft"),
            Alert(title="Urban flooding advisory draft", severity="high", affected_locations="Mumbai, Hyderabad", message="Synthetic alert generated by demo scenario.", language="en", simulated=True, status="draft"),
        ]
        db.add_all(incidents + resources + alerts)
        db.add(AuditLog(action="demo_replay", message=f"Loaded synthetic scenario: {scenario}"))
        db.commit()
        return {"status": "simulated", "scenario": scenario, "message": "Synthetic demo records loaded. They are clearly marked as demo data and are not live alerts.", "counts": {"incidents": len(incidents), "resources": len(resources), "alerts": len(alerts)}}
    finally:
        db.close()


@router.post("/reset")
def reset_demo():
    db = SessionLocal()
    try:
        db.query(Incident).filter(Incident.source == "demo").delete(synchronize_session=False)
        db.query(Alert).filter(Alert.simulated.is_(True)).delete(synchronize_session=False)
        db.query(Resource).filter(or_(Resource.name == "NDRF response unit", Resource.name == "Inflatable rescue boats", Resource.name == "Medical support kits")).delete(synchronize_session=False)
        db.add(AuditLog(action="demo_reset", message="Removed synthetic demo records"))
        db.commit()
        return {"status": "reset", "message": "Synthetic demo records removed."}
    finally:
        db.close()
